services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  common:
    build:
      context: ./pixiescale-common
    volumes:
      - maven-repo:/root/.m2/repository

  mediaingestion:
    build:
      context: ./pixiescale-mediaingestion
      dockerfile: Dockerfile
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    volumes:
      - media-uploads:/app/media/uploads
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms256m -Xmx512m

  jobmanagement:
    build:
      context: ./pixiescale-jobmanagement
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - redis
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms256m -Xmx512m

  transcodingworker:
    build:
      context: ./pixiescale-transcodingworker
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - mediaingestion
    ports:
      - "8083:8083"
    volumes:
      - media-uploads:/app/media/uploads
      - media-output:/app/output
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms256m -Xmx512m

  mediastorage:
    build:
      context: ./pixiescale-mediastorage
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - transcodingworker
    ports:
      - "8084:8084"
    volumes:
      - media-transcoded:/app/media/transcoded
      - media-output:/app/output:ro
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms256m -Xmx512m

  apigateway:
    build:
      context: ./pixiescale-apigateway
      dockerfile: Dockerfile
    depends_on:
      - mediaingestion
      - jobmanagement
      - transcodingworker
      - mediastorage
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms256m -Xmx512m

volumes:
  media-uploads:
  media-output:
  media-transcoded:
  maven-repo: