spring:
  application:
    name: pixiescale

  profiles:
    active: local

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    com.pixiescale: DEBUG

ffmpeg:
  binary-path: ffmpeg
  temp-dir: ${java.io.tmpdir}/pixiescale
  timeout-seconds: 3600
  gpu-acceleration: false
  gpu-device: "0"

storage:
  type: local
  base-dir: ${user.home}/pixiescale/media
  upload-part-size: 5
  max-upload-size: 2000