server:
  port: 8080

spring:
  application:
    name: pixiescale-apigateway
  cloud:
    gateway:
      routes:
        - id: mediaingestion
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/media/**
        - id: jobmanagement
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/jobs/**
        - id: transcodingworker
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/transcoding/**
        - id: mediastorage
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/storage/**
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
        - AddResponseHeader=X-Api-Gateway, PixieScale

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    com.tenacy.pixiescale: DEBUG
    org.springframework.cloud.gateway: DEBUG